# Generated by Django 4.1.7 on 2023-03-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(default='xyz@abc.com', max_length=254)),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
    ]
