# Generated by Django 4.1.7 on 2023-03-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_alter_registeredusersmodel_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredusersmodel',
            old_name='name',
            new_name='username',
        ),
    ]
