# Generated by Django 4.1.7 on 2023-03-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0003_rename_name_registeredusersmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusersmodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
