# Generated by Django 4.1.7 on 2023-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0004_alter_registeredusersmodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredusersmodel',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
